"""Stable hardware contract, including explicit execution completion detection."""

from pathlib import Path
from typing import Protocol

from fl_common.models.base import Schema


class RunResult(Schema):
    passed: bool
    exit_code: int = 0
    detail: str | None = None


class BoardBackend(Protocol):
    async def discover(self) -> dict[str, str]: ...
    async def power_on(self) -> None: ...
    async def power_off(self) -> None: ...
    async def set_voltage(self, rail: int, volts: float) -> None: ...
    async def read_voltage(self, channel: int) -> float: ...
    async def read_current(self, channel: int) -> float: ...
    async def set_frequency(self, hz: float) -> None: ...
    async def program_fpga(self, bitstream: Path) -> None: ...
    async def program_soc(self, elf: Path) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def read_uart(self) -> bytes: ...
    async def wait_for_completion(self) -> RunResult: ...
